#!/bin/bash -eu
#
# Copyright 2016 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
################################################################################
echo "umask=$(umask)"

umask 022
. build

echo ========== RUNNING FUZZER ==========
for F in $FUZZERS; do
  FUZZER_ADDITIONAL_OPTIONS=""
  if  [ -n "$FUZZER_DICTIONARY" ]; then
    FUZZER_ADDITIONAL_OPTIONS="$FUZZER_ADDITIONAL_OPTIONS -dict=$FUZZER_DICTIONARY"
  fi
  CORPUS="/work/corpuses/$(basename $F)"
  mkdir -p $CORPUS
  cd $(dirname $F)
  FUZZER_ADDITIONAL_OPTIONS="$FUZZER_ADDITIONAL_OPTIONS $CORPUS"
  env ASAN_OPTIONS=$ASAN_OPTIONS $F $FUZZER_OPTIONS $FUZZER_ADDITIONAL_OPTIONS
done
