#!/bin/bash -eu
#
# Copyright 2016 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
################################################################################

OLD_ASAN_OPTIONS=$ASAN_OPTIONS
OLD_CFLAGS=$CFLAGS
OLD_CXX_FLAGS=$CXXFLAGS
OLD_PATH=$PATH

echo ========== BUILDING CLANG ==========
bash $BASH_FLAGS /src/scripts/build_clang.sh

export CFLAGS="$CFLAGS $SANITIZER_OPTIONS $COVERAGE_OPTIONS"
export CXXFLAGS="$CXXFLAGS $SANITIZER_OPTIONS $COVERAGE_OPTIONS"

# build libfuzzer
mkdir -p /work/libfuzzer
cd /work/libfuzzer
for f in /src/llvm/lib/Fuzzer/*cpp; do
  $CXX -std=c++11 $OLD_CXXFLAGS $SANITIZER_OPTIONS -IFuzzer -c $f &
done
wait

export LIBFUZZER_OBJS="/work/libfuzzer/*.o"
mkdir -p /work/logs

echo ========== BUILDING PROJECT ========
# asan could get in the way of configure scripts.
export ASAN_OPTIONS=""
bash $BASH_FLAGS /src/scripts/build.sh 2>&1 >> /work/logs/build.log

export ASAN_OPTIONS=$OLD_ASAN_OPTIONS
