
def libfuzzerBuild = fileLoader.fromGit('dockerfiles/pipeline.groovy',
        'https://github.com/google/libfuzzer-bot.git', 'master', null, '')

libfuzzerBuild {
  git = "git://git.sv.nongnu.org/freetype/freetype2.git"
  dockerfile = "libfuzzer-bot/dockerfiles/freetype2/Dockerfile"
}
