
def libfuzzerBuild = fileLoader.fromGit('dockerfiles/pipeline.groovy',
        'https://github.com/google/libfuzzer-bot.git', 'master', null, '')

libfuzzerBuild {
  git = "https://github.com/openssl/openssl"
  dockerfile = "libfuzzer-bot/dockerfiles/openssl/Dockerfile"
}
